### ISSUE TITLE
[PE-D][Tester C] Birthday Bug

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T14-3/tp#115]
### Description

Adding birthdate of 30-02-2021 automatically changes the birthday to 28-02-2021

### Steps to reproduce bug

1. Enter `add n/John Doe b/30-02-2021 p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 t/DustAllergy`

![image.png](https://raw.githubusercontent.com/changjy44/ped/main/files/738b5db7-cd9b-412b-aa50-fb56003692dd.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: changjy44/ped#2

**Comment by marclzh** [comment]
This issue is due to Java's LocalDateTime API, and will be further clarified in the UG and DG that it will be autocorrected based on the calendar. Valid dates, i.e. 1-31 will be accepted and references the actual calendar. If date is out of range, but valid, the date will be rounded down to the last possible date of the month.
